GoogleCloudPlatform/pubsub

kafka-connector/pom.xml

grpc-all upgrade

---

load-test-framework/pom.xml
load-test-framework/src/main/java/com/google/pubsub/flic/Driver.java
load-test-framework/src/main/java/com/google/pubsub/flic/common/LatencyDistribution.java
load-test-framework/src/main/java/com/google/pubsub/flic/controllers/Client.java
load-test-framework/src/main/java/com/google/pubsub/flic/controllers/ClientParams.java
load-test-framework/src/main/java/com/google/pubsub/flic/controllers/GCEController.java
load-test-framework/src/main/java/com/google/pubsub/flic/output/SheetsService.java
load-test-framework/src/test/java/com/google/pubsub/flic/output/SheetsServiceTest.java

The stats generated by the test are packaged and outputted directly to a Google Sheets document, set by user by environment variable LOADTEST_SPREADSHEET_ID.

Load test stats output to Google Sheets

---

load-test-framework/src/main/java/com/google/pubsub/clients/common/LoadTestRunner.java

Previously, an ArrayBlockingQueue is used to prevent LoadTestRunner from
running out of memory.
However, when thread pool is fully loaded and the queue is full,
ThreadPoolExecutor rejects new tasks and call its
RejectedExecutionHandler.
By default, the handler throws an exception to the thread trying to
submit the new task.
Consequently, the load tester dies and the test hangs forever.
This commit fixes this by using DiscardPolicy, which silently
drops all rejected tasks.

fix thread-death LoadTestRunner

---

load-test-framework/pom.xml
load-test-framework/src/main/java/com/google/pubsub/clients/gcloud/CPSPublisherTask.java
load-test-framework/src/main/java/com/google/pubsub/clients/gcloud/CPSSubscriberTask.java
load-test-framework/src/main/java/com/google/pubsub/clients/vtk/CPSPublisherTask.java

I verified that tests are working. However, we should not submit this, until `google-cloud-pubsub` publishes `0.9.3-alpha` (without the SNAPSHOT). Otherwise all builds will fail.

update gcloud Tasks with high perf client

---

jms-light/pom.xml

Figuring out how to work with github

Fixing POM file to get rid of maven warnings

---

jms-light/src/main/java/com/google/pubsub/jms/light/destination/PubSubTemporaryTopic.java

Add PubSubTemporaryTopic class

---

jms-light/src/main/java/com/google/pubsub/jms/light/PubSubTopicSession.java

Implement PubSubTopicSession class

---

jms-light/src/main/java/com/google/pubsub/jms/light/PubSubTopicConnectionFactory.java

Create a TopicConnectionFactory

---

jms-light/src/main/java/com/google/pubsub/jms/light/PubSubTopicConnection.java

Implement PubSubTopicConnection class

---

jms-light/pom.xml
jms-light/src/main/java/com/google/pubsub/jms/light/PubSubTopicConnectionFactory.java
jms-light/src/main/java/com/google/pubsub/jms/light/PubSubTopicSession.java
jms-light/src/test/java/com/google/pubsub/jms/light/integration/BaseIntegrationTest.java
jms-light/src/test/java/com/google/pubsub/jms/light/integration/PublisherIntegrationTest.java

Cleaned code style, especially for test classes. This addresses Github JMS issue #92.

Cleaned code style, especially for test classes

---

kafka-connector/config/cps-sink-connector.properties
kafka-connector/config/cps-source-connector.properties

* Change config name for source and sink from CPSConnector
to CPSSourceConnector and CPSSinkConnector respectively.

Create unique names in Kafka Connector config (#161)

---

README.md
client/README.md

Update Pub/Sub Client links

---

load-test-framework/pom.xml

Add javax.annotation dependency.

---

kafka-connector/pom.xml
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubGRPCSubscriber.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubRoundRobinSubscriber.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceConnector.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSubscriber.java
kafka-connector/src/test/java/com/google/pubsub/kafka/source/CloudPubSubSourceTaskTest.java

fix: Update dependencies to versions without known security vulnerabilities

---

kafka-connector/README.md
kafka-connector/config/pubsub-lite-source-connector.properties
kafka-connector/pom.xml
kafka-connector/src/main/java/com/google/pubsublite/kafka/sink/PubSubLiteSinkConnector.java
kafka-connector/src/main/java/com/google/pubsublite/kafka/source/ConfigDefs.java
kafka-connector/src/main/java/com/google/pubsublite/kafka/source/Poller.java
kafka-connector/src/main/java/com/google/pubsublite/kafka/source/PollerFactory.java
kafka-connector/src/main/java/com/google/pubsublite/kafka/source/PollerFactoryImpl.java
kafka-connector/src/main/java/com/google/pubsublite/kafka/source/PollerImpl.java
kafka-connector/src/main/java/com/google/pubsublite/kafka/source/PubSubLiteSourceConnector.java
kafka-connector/src/main/java/com/google/pubsublite/kafka/source/PubSubLiteSourceTask.java
kafka-connector/src/test/java/com/google/pubsublite/kafka/sink/PubSubLiteSinkTaskTest.java
kafka-connector/src/test/java/com/google/pubsublite/kafka/source/PollerImplTest.java
kafka-connector/src/test/java/com/google/pubsublite/kafka/source/PubSubLiteSourceTaskTest.java

feat: Implement Pub/Sub Lite Source Connector

---

.github/workflows/new-release.yml

This will make a new release and build an uber-jar whenever a tag structured like 'v<something>' like 'v0.8.0' is set on master
fixes #191

feat: Create new release github workflow

---

kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java

Call setEnableMessageOrdering if an ordering key source is provided

---

kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceConnector.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java

These control num pullers, max ack extension period and max duration per ack extension.

Add new parameters to source connector 

---

kafka-connector/README.md

Clarify flow control parameter descriptions

Clarify flow control parameter descriptions

---

load-test-framework/src/main/java/com/google/pubsub/flic/controllers/Client.java

Add more info to logs when unable to connect to client

---

kafka-connector/pom.xml

Fix build for aarch64 closing #301

Update Netty dependency

---

load-test-framework/src/main/java/com/google/pubsub/flic/controllers/resource_controllers/GCEComputeResourceController.java
load-test-framework/src/main/resources/gce/cps-gcloud-go-publisher_startup_script.sh
load-test-framework/src/main/resources/gce/cps-gcloud-go-subscriber_startup_script.sh
load-test-framework/src/main/resources/gce/cps-gcloud-java-publisher_startup_script.sh
load-test-framework/src/main/resources/gce/cps-gcloud-java-subscriber_startup_script.sh
load-test-framework/src/main/resources/gce/cps-gcloud-node-publisher_startup_script.sh
load-test-framework/src/main/resources/gce/cps-gcloud-node-subscriber_startup_script.sh

Partially resolves #323, as the startup scripts on the VMs were failing due to the wrong `gsutil` path.

fix(load-test): update startup scripts with new gsutil path

---

CONTRIBUTING.md
flink-connector/CONTRIBUTING.md
flink-connector/README.md

Establish an initial collaboration model for the CPS Flink connector and guidelines for contributing.

Add contribution guide for CPS flink connector

---

.kokoro/linkage-monitor.sh
.kokoro/nightly/java11-integration.cfg
.kokoro/nightly/java11.cfg
.kokoro/nightly/java7.cfg
.kokoro/nightly/java8-osx.cfg
.kokoro/nightly/java8-win.cfg
.kokoro/nightly/java8.cfg
.kokoro/nightly/samples.cfg
.kokoro/presubmit/clirr.cfg
.kokoro/presubmit/dependencies.cfg
.kokoro/presubmit/graalvm-native-17.cfg
.kokoro/presubmit/graalvm-native.cfg
.kokoro/presubmit/java11.cfg
.kokoro/presubmit/java7.cfg
.kokoro/presubmit/java8-osx.cfg
.kokoro/presubmit/java8-win.cfg
.kokoro/presubmit/java8.cfg
.kokoro/presubmit/linkage-monitor.cfg
.kokoro/presubmit/lint.cfg
.kokoro/presubmit/samples.cfg

- Add cfg files in presubmit and nightly build configs

chore: add cfg files for nightly builds and presubmit builds

---

.kokoro/build.sh
.kokoro/presubmit/integration.cfg

- Update secret in presubmit integration
- Update flag in build.sh

chore: debug presubmit integration
