GoogleCloudPlatform/pubsub

load-test-framework/src/main/java/com/google/pubsub/flic/output/SheetsService.java
load-test-framework/src/test/java/com/google/pubsub/flic/output/SheetsServiceTest.java

Discovered when building from head that the tests still try to authorize access to the user's sheets, which I didn't realize earlier because my branch had it all cached. This simple fix will throw a null pointer when trying to access the credentials file, which is caught by the constructor. Now, the test doesn't try to set up a sheets service, so it doesn't ask for the user to log into their google account.

Simple sheets unit test fix

---

load-test-framework/src/main/java/com/google/pubsub/flic/Driver.java
load-test-framework/src/main/resources/gce/cps-gcloud-java-publisher_startup_script.sh
load-test-framework/src/main/resources/gce/cps-gcloud-java-subscriber_startup_script.sh
load-test-framework/src/main/resources/gce/kafka-publisher_startup_script.sh
load-test-framework/src/main/resources/gce/kafka-subscriber_startup_script.sh

Installing java 8 is failing on all runs of framework due to a change in ubuntu's repository for the jdk. To prevent this from happening again, added apt-get update to the startup scripts.
Also moved creation of Client.startime higher up in the Driver class to avoid null pointer at line 267

Script fixes

---

kafka-connector/src/main/java/com/google/pubsub/kafka/common/ConnectorUtils.java

Hi, I'm from the gRPC team and it seems like you are referencing a gRPC class that is soon going to be visibility restricted.  This change fixes the code to not have such a reference.

Don't reference gRPC internal classes

---

load-test-framework/src/main/java/com/google/pubsub/flic/controllers/GCEController.java

Previously, we used InputStreamContent to upload files.
This seems to have a problem with large files such as driver.jar.
This commit changes to FileContent instead.

Use FileContent to upload files

---

load-test-framework/flic.iml
load-test-framework/pom.xml
load-test-framework/src/main/java/com/google/pubsub/flic/Driver.java
load-test-framework/src/main/java/com/google/pubsub/flic/controllers/Client.java
load-test-framework/src/main/java/com/google/pubsub/flic/controllers/GCEController.java
load-test-framework/src/main/java/com/google/pubsub/flic/output/SheetsService.java
load-test-framework/src/main/proto/loadtest.proto

Kafka topics are now automatically deleted and recreated upon running a loadtest; this ensures no backlog in topics causing performance issues. 
Address of zookeeper hosts will now be a required flag when running a test with Kafka brokers.

Kafka loadtest modifications.

---

.travis.yml
client/src/main/java/com/google/cloud/pubsub/AbstractSubscriberConnection.java
client/src/test/java/com/google/cloud/pubsub/SubscriberImplTest.java
client/src/test/resources/log4j.xml
client/src/test/resources/logging.properties
jms-light/src/test/resources/logging.properties

- _AbstractSubscriberConnection#addOutstadingAckHandlers_ java 1.8 construction (..putIfAbsent) has been replaced with [V v = map.get(key); if (v == null) v = map.put(key, value);](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#putIfAbsent-K-V-)
- _SubscriberImplTest#testReceiverError_NacksMessage_ looks like unstable  and failed in most travis builds.  _Thread.sleep(200)_ helped, better solution should be provided.
- _.travis.yaml_ scripts has been updated with different jdk versions, all projects builds with jdk 1.7/1.8 except 'load-test-framework'

Client code has been modified to be compatible with jdk1.7.

---

load-test-framework/src/main/java/com/google/pubsub/clients/common/LoadTestRunner.java
load-test-framework/src/main/java/com/google/pubsub/clients/common/Task.java

This commit makes LoadTestRunner block when the task queue of its
executor is full.
Previously the LTR would discard the old task and immediate queue a new
one. Depending on how CPU resource is shared between threads and
processes, this could starve the process under test.
cc @mdietz94 @jba @garrettjonesgoogle

make LoadTestRunner back off

---

load-test-framework/run.py
load-test-framework/src/main/java/com/google/pubsub/clients/adapter/AdapterTask.java
load-test-framework/src/main/java/com/google/pubsub/flic/Driver.java
load-test-framework/src/main/java/com/google/pubsub/flic/controllers/Client.java
load-test-framework/src/main/java/com/google/pubsub/flic/output/SheetsService.java
load-test-framework/src/main/resources/gce/cps-gcloud-go-publisher_startup_script.sh

This PR also fixes a race in AdapterTask.
Previously it issues a StartRequest to the worker process without
waiting for the RPC to complete.
Consequently, the load test might happen before the worker process
could process the StartRequest.
This is fixed by making AdapterTask wait for the request to return.
The Go support is incomplete.
The program expects the binary to be available at gs://BUCKET/loadtest-go,
but does not automatically upload it there.
If possible, I'd like to land this automation in a separate PR to unblock my work
on load testing Go subscriber implementation.
cc @jba

add go publisher

---

jms-light/src/main/java/com/google/pubsub/jms/light/PubSubTopic.java
jms-light/src/test/java/com/google/pubsub/jms/light/publisher/GeneralTopicTest.java

#66 
The PubSubTopic class has already been implemented as PubSubTopicDestination in com.google.pubsub.jms.light.destination.
Replacing the PubSubTopic class with PubSubTopicDestination class in test.

Replace PubSubTopic class with existing PubSubTopicDestination class

---

jms-light/pom.xml
jms-light/src/main/java/com/google/pubsub/jms/light/PubSubConnection.java
jms-light/src/main/java/com/google/pubsub/jms/light/PubSubConnectionFactory.java
jms-light/src/main/java/com/google/pubsub/jms/light/PubSubMessageProducer.java
jms-light/src/test/java/com/google/pubsub/jms/light/integration/BaseIntegrationTest.java
jms-light/src/test/java/com/google/pubsub/jms/light/integration/PublisherIntegrationTest.java

PR following Issue #75. I open it now so people can start implementing the missing classes based on the new library version.
It includes the minimal set of changes to make the module build, but the test are still failing. Also, I had to comment out the tests in the *integration* package since the new version of google-cloud-pubsub removed the *deprecated* package completely.
I suggest we keep this as is (or remove the files completely) until we decide an approach (issue #72).

Jms version upgrade

---

kafka-connector/pom.xml
kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java

Hello there! Thanks for putting together this connector! I made a couple quick changes to the dependencies. The kafka dependencies should be in the provided scope since they are hosted in the connect worker process. I also moved the testing dependencies to the test scope. This should reduce the overall size of the output artifact.

Dependency cleanup

---

jms-light/pom.xml
jms-light/src/main/java/com/google/pubsub/jms/light/message/PubSubTextMessage.java

This is the configuration that I used. With this, I get the following warnings (the second one is probably independent of -Xlint):
...
[WARNING] /usr/local/google/home/uhu/src/pubsub/jms-light/src/main/java/com/google/pubsub/jms/light/message/PubSubTextMessage.java:[39,16] unchecked cast
required: T
found:    java.lang.String
...
[WARN] /usr/local/google/home/uhu/src/pubsub/jms-light/src/main/java/com/google/pubsub/jms/light/PubSubTopicSession.java:9: Wrong lexicographical order for 'com.google.pubsub.jms.light.destination.PubSubTemporaryTopic' import. Should be before 'javax.jms.TemporaryTopic'. [CustomImportOrder]
[WARN] /usr/local/google/home/uhu/src/pubsub/jms-light/src/main/java/com/google/pubsub/jms/light/PubSubTopicConnectionFactory.java:12: Line is longer than 100 characters …

Xlint Configuration

---

kafka-connector/pom.xml

Just adding ${os.detected.classifier} to Pom so the right netty-tcnative-boring-ssl-static library is selected.
This is to ensure the connector can work in any OS (e.g. OSX).

Adding ${os.detected.classifier} to Pom

---

kafka-connector/pom.xml

A slightly better approach than PR #115, which adds the (unneeded) guava dependency.

Shade the guava library to avoid a NoMethodFoundError 

---

kafka-connector/README.md

Some newlines snuck their way into these links
Thanks for the project!

Fix some broken markdown in the README

---

load-test-framework/src/main/java/com/google/pubsub/clients/gcloud/CPSSubscriberTask.java

Shutting down needs to wait for messages to be processed,
and processing the messages need to lock the Task object.
So, if the thread calling shutdown locks the Task object, we'll
deadlock.

java: don't sync on shutdown

---

load-test-framework/pom.xml
load-test-framework/src/main/java/com/google/pubsub/clients/gcloud/CPSSubscriberTask.java

The new default number of parallel pullers is NumCPU.
To keep up with publishers, we need to increase the number of pullers.
This commit increaes the number to 5*NumCPU,
the same as the old default.

increase parallel puller count

---

kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java
kafka-connector/src/test/java/com/google/pubsub/kafka/source/CloudPubSubSourceTaskTest.java

The idea is not to produce duplicates in Kafka if Pub/sub ack fails. We can achieve that by managing ack ids in callbacks.

No duplicates in Kafka when ack fails

---

kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java
kafka-connector/src/test/java/com/google/pubsub/kafka/source/CloudPubSubSourceTaskTest.java

Current implementation acks pub/sub messages in the beginning of pull method which means that it takes two pull cycles to send messages to Kafka and acknowledge them after. Whenever you stop Kafka connector, the messages from the last cycle would get delivered to Kafka but acknowledge of pub/sub messages would not happen. This produces ( cps.maxBatchSize * tasks.max) duplicates on every stop of Kafka connector. 
Provided implementation uses SourceTask commit hook to acknowledge pub/sub messages.

Acknowledge Cloud Pub/Sub messages in commit hook

---

kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java

Think that would be nice to have pub/sub timestmap information in Kafka. That way you can more easily relate messages between those two systems.

Preserve timestamp information from pub/sub message

---

kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java
kafka-connector/src/test/java/com/google/pubsub/kafka/source/CloudPubSubSourceTaskTest.java

Ack was accidentally removed from poll method which prevented pub/sub messages to be acknowledged ( they would only get eventually acknowledged in connector shutdown ).

Ack was accidentally gone

---

kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceConnector.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java
kafka-connector/src/test/java/com/google/pubsub/kafka/source/CloudPubSubSourceTaskTest.java

When moving messages from Pubsub to Kafka, Kafka message ingress time is set to Pubsub message publish time. In some cases would be more appropriate to set Kafka ingress time to some other time (eg. event time contained in the payload). This way the semantics and reasoning about time is the same across different systems ( Kafka supports traversing through message offset by time so being able to control ingress time is important for many scenarios like backup/restore )

Adding timestamp message attribute 

---

kafka-connector/README.md
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceConnector.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java
kafka-connector/src/test/java/com/google/pubsub/kafka/source/CloudPubSubSourceTaskTest.java

New scheme relies on kafka producer to do the partitioning, which by default provides stable hashing based on message key or round robin if no key is specified. Number of partitions is automatically inferred by kafka producer.
Partially adresses https://github.com/GoogleCloudPlatform/pubsub/issues/171

add kafka_partitioner partition scheme

---

kafka-connector/README.md
kafka-connector/src/main/java/com/google/pubsub/kafka/common/ConnectorCredentialsProvider.java
kafka-connector/src/main/java/com/google/pubsub/kafka/common/ConnectorUtils.java
kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkConnector.java
kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubGRPCSubscriber.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubRoundRobinSubscriber.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceConnector.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java
kafka-connector/src/test/java/com/google/pubsub/kafka/source/CloudPubSubSourceConnectorTest.java

Add support for passing in JSON credentials via connector config key 'gcp.credentials.json'.

kafka-connector: support explicit json credentials

---

kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkConnector.java
kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java
kafka-connector/src/test/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTaskTest.java

This change fixes PubSub connector leaking threads when there are periodic connector's configuration updates. On each configuration update Kafka Connect stops and starts connector tasks.
Before applying the change we observed ~120 threads at Kafka Connect's startup growing to 2k+ threads after a few hours of configuration updates.
After the change the day's worth of updates does not impact the number of Kafka Connect's threads and their numbers stays at ~120.
Fixes: #201

Fix threads leak on sink task stop by shutting down publisher

---

kafka-connector/pom.xml

Fixes https://github.com/GoogleCloudPlatform/pubsub/issues/210
Saw the PubSub connector report errors like the following when trying to access PubSub using a Kafka Connect Docker image based on Alpine Linux:
```
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so
at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
... 27 more
Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
at java.lang.Runtime.loadLibrary0(Runtime.java:870)
at java.lang.System.loadLibrary(System.java:1122)
at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:316) …
```

Upgrade GRPC and PubSub client dependencies.

---

kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java

Instead, only drop the single message received.

fix: Do not drop all messages in the batch when receiving an empty message

---

kafka-connector/README.md
kafka-connector/config/pubsub-lite-source-connector.properties
kafka-connector/copy_tool.py
load-test-framework/flic.iml

This is a simple tool intended for quickstart usecases. Given only a list of kafka servers to connect to and a connector config file, it handles downloading, installing and running a standalone connector instance.

feat: Implement copy_tool

---

kafka-connector/pom.xml
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubGRPCSubscriber.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubRoundRobinSubscriber.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceConnector.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSourceTask.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/CloudPubSubSubscriber.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/StreamingPullSubscriber.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/StreamingPullSubscriberFactory.java
kafka-connector/src/main/java/com/google/pubsub/kafka/source/StreamingPullSubscriberImpl.java
kafka-connector/src/test/java/com/google/pubsub/kafka/source/CloudPubSubSourceTaskTest.java
kafka-connector/src/test/java/com/google/pubsub/kafka/source/StreamingPullSubscriberTest.java

Also rework interfaces to not be tightly coupled with pull requests.
The implementation here is largely copied from the Pub/Sub Lite BlockingPullSubscriberImpl (https://github.com/googleapis/java-pubsublite/blob/master/google-cloud-pubsublite/src/main/java/com/google/cloud/pubsublite/internal/BlockingPullSubscriberImpl.java) with modifications made to make it work with Cloud Pub/Sub clients instead of Pub/Sub lite wire clients.

feat: Implement Streaming pull CloudPubSubSubscriber

---

ordering-keys-prober/src/main/java/com/google/cloud/pubsub/prober/ProberStarter.java

Per https://jcommander.org/#_boolean, arity needs to be set for default enabled boolean flag

Fix ordered_delivery option to be settable

---

kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkConnector.java

Make the maximum buffer size 9.5 MB instead of 10 MB to prevent errors.

---

kafka-connector/README.md
kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkConnector.java
kafka-connector/src/main/java/com/google/pubsub/kafka/sink/CloudPubSubSinkTask.java

Allowing the flow controls to limit the max outstanding bytes and elements. During large traffic spikes, we have observed Connect playing messages into the PubSub producer client as fast as possible resulting in several GB of off heap usage causing OOM errors. Configuring the connector to block on maxOutstandingRequestBytes should prevent this and stop polling until space is available.
We've tested this both with  the default and with a specified low maxOutstandingRequestBytes in our loadtest environment and observed it working as expected.
I've set the default values to Long. MAX_VALUE to effectively preserve the existing behavior for anyone that may not want this change, but I'm open to setting these to a reasonable value if we have some consensus on what that is.

Add blocking flow controls to the PubSub Sink connector

---

load-test-framework/src/main/java/com/google/pubsub/flic/controllers/resource_controllers/PubsubResourceController.java

Use SLF4J's parameterized messages for better
performance \[1\].
Also fix one log that incorrectly called a topic a subscription.
Logs before
```
ERROR-Error creating subscription
406 [pool-1-thread-4] ERROR com.google.pubsub.flic.controllers.resource_controllers.PubsubResourceController  - Error creating subscription
```
Logs after
```
ERROR-Error creating topic cloud-pubsub-loadtest
419 [pool-1-thread-3] ERROR com.google.pubsub.flic.controllers.resource_controllers.PubsubResourceController  - Error creating topic cloud-pubsub-loadtest
```
1: http://www.slf4j.org/faq.html#logging_performance

Add more info to logs

---

load-test-framework/src/main/java/com/google/pubsub/flic/controllers/resource_controllers/GCEComputeResourceController.java

fix: use ubuntu-2004-focal-v20210720 as GCE VM source image

---

README.md
kafka-connector/README.md

Set up redirect for Kafka connector, which has been moved to https://github.com/googleapis/java-pubsub-group-kafka-connector and has a release pending for the week of 9/26.

docs: deprecate kafka connector and add a redirect

---

flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/PubSubSource.java
flink-connector/flink-connector-gcp-pubsub/src/test/java/com/google/pubsub/flink/PubSubSourceTest.java

Default flow control values are copied from the CPS client library. `FlowControlSettings` cannot be added as a builder option due to it not being serializable.
Max outstanding values are per-checkpoint. I plan to document how flow control works in a separate PR.

Add flow control setting to source builder

---

README.md
flink-connector/README.md
flink-connector/docs/content/docs/connectors/datastream/pubsub.md

This PR documents how `PubSubSink` works in `flink-connector/docs/content/docs/connectors/datastream/pubsub.md`, loosely following the documentation structure used by similar Flink connectors. Feel free to suggest changes to the structure.

Add initial documentation for Flink connector

---

flink-connector/docs/content/docs/connectors/datastream/pubsub.md
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/PubSubSink.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/PubSubSource.java
flink-connector/flink-connector-gcp-pubsub/src/test/java/com/google/pubsub/flink/PubSubSinkTest.java
flink-connector/flink-connector-gcp-pubsub/src/test/java/com/google/pubsub/flink/PubSubSourceTest.java

These are commonly used builder options in the underlying Pub/Sub client library.

Add builder options to source/sink

---

flink-connector/docs/content/docs/connectors/datastream/pubsub.md
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/internal/source/enumerator/PubSubSplitEnumerator.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/internal/source/reader/AckTracker.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/internal/source/reader/PubSubAckTracker.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/internal/source/reader/PubSubNotifyingPullSubscriber.java
flink-connector/flink-connector-gcp-pubsub/src/test/java/com/google/pubsub/flink/internal/source/reader/PubSubAckTrackerTest.java
flink-connector/flink-connector-gcp-pubsub/src/test/java/com/google/pubsub/flink/internal/source/reader/PubSubNotifyingPullSubscriberTest.java

This PR addresses a lack of at-least-once guarantee in PubSubSource and undesired behavior when recovering from a fault.
This PR adds an at-least-once guarantee by deferring adding messages to the AckTracker from when they are delivered to when SplitReader calls fetch on them. This prevents messages from being added to a checkpoint before the SplitReader fetches them.
When recovering from a fault, PubSubSplitReader would receive their previously assigned splits + new splits. Since splits are never finished (there's no notion of partitions in CPS), this would lead to each PubSubSplitReader accumulating addtion subscribers to manage whenever recovering from a failure. The ideal behavior is having a one-to-one mapping of subscriber clients to parallelism. This is achived by keying splits by …

Add at-least-once delivery guarantee to CPS source

---

flink-connector/docs/content/docs/connectors/datastream/pubsub.md
flink-connector/flink-connector-gcp-pubsub-e2e-tests/pom.xml
flink-connector/flink-connector-gcp-pubsub-e2e-tests/src/test/java/com/google/pubsub/flink/DockerImageVersions.java
flink-connector/flink-connector-gcp-pubsub-e2e-tests/src/test/java/com/google/pubsub/flink/PubSubEmulatorHelper.java
flink-connector/flink-connector-gcp-pubsub-e2e-tests/src/test/java/com/google/pubsub/flink/PubSubSinkEmulatorTest.java
flink-connector/flink-connector-gcp-pubsub-e2e-tests/src/test/java/com/google/pubsub/flink/PubSubSourceEmulatorTest.java
flink-connector/flink-connector-gcp-pubsub/pom.xml
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/PubSubSink.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/PubSubSource.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/util/EmulatorEndpoint.java
flink-connector/pom.xml

- Add support for source/sink connecting to an emulator using `builder.setEndpoint`
- In E2E tests, start a docker container with a running CPS emulator if the env var PUBSUB_EMULATOR_HOST is not set
- Write a simple E2E test where PubSubSink publishes to an emulator

Dockerize E2E emulator tests and add an E2E test for PubSubSink

---

flink-connector/README.md
flink-connector/docs/content/docs/connectors/datastream/pubsub.md
flink-connector/flink-connector-gcp-pubsub-e2e-tests/pom.xml
flink-connector/flink-connector-gcp-pubsub/pom.xml
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/PubSubSink.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/PubSubSource.java
flink-connector/flink-examples-gcp-pubsub/pom.xml
flink-connector/flink-examples-gcp-pubsub/pubsub-streaming/pom.xml
flink-connector/flink-examples-gcp-pubsub/pubsub-streaming/src/main/java/com/google/pubsub/flink/PubSubExample.java
flink-connector/pom.xml

- Make the example parameters more clear
- Add parsing for fully-qualified topic/subscription names
- Add a quickstart guide in the README for building, running, and verifying the example job
- Add more code samples to pubsub.md (more to come)

Improve example Flink job and documentation

---

flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/PubSubSource.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/internal/source/reader/AckTracker.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/internal/source/reader/PubSubAckTracker.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/internal/source/reader/PubSubNotifyingPullSubscriber.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/internal/source/reader/PubSubRecordEmitter.java
flink-connector/flink-connector-gcp-pubsub/src/main/java/com/google/pubsub/flink/internal/source/reader/PubSubSourceReader.java
flink-connector/flink-connector-gcp-pubsub/src/test/java/com/google/pubsub/flink/internal/source/reader/PubSubAckTrackerTest.java
flink-connector/flink-connector-gcp-pubsub/src/test/java/com/google/pubsub/flink/internal/source/reader/PubSubNotifyingPullSubscriberTest.java
flink-connector/flink-connector-gcp-pubsub/src/test/java/com/google/pubsub/flink/internal/source/reader/PubSubRecordEmitterTest.java
flink-connector/flink-connector-gcp-pubsub/src/test/java/com/google/pubsub/flink/internal/source/reader/PubSubSourceReaderTest.java

This PR is a follow-up to https://github.com/GoogleCloudPlatform/pubsub/pull/362, which deferred the call to `AckTracker.addPendingAck` until the message was fetched. That change is insufficient to guarantee at-least-once delivery, since this race condition is possible:
1. A message is fetched and added to `SourceReaderBase.elementsQueue` (the message's ack is pending)
2. `SourceReaderBase.snapshotState` is called, which calls `AckTracker.addCheckpoint(checkpointId)` (the message is added to `checkpointId` before calling `RecordEmitter.emitRecord` with the message)
3. `SourceReaderBase.notifyCheckpointComplete` is called, which calls `AckTracker.notifyCheckpointComplete` to ack the message (there's no guarantee that `RecordEmitter.emitRecord` was called before acking the message)
4. The …

Do not add source messages to a checkpoint until after it is emitted
